# Generated by Django 3.2.3 on 2021-05-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210530_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/images/'),
        ),
    ]
